const dbConfig = require("./data/dbConfig");
const candies = require("./data/candies");
// const questions = require("./data/emoji/movie");
// const questions = require("./data/pastokq");
const questions = [
	"food or travel",
	"sinigang o adobo",
	"umaga o gabi",
	"face or personality",
	"toblerone or hershey's",
	"reese's or snickers",
	"yes or No, Mahal mo na ba crush mo",
	"sex or chocolates",
	"pizza or burger",
	"Magising sa katotohanan or mabuhay sa kasinungalingan",
	"Yes or No, Magaling ka ba sa Calculus",
	"one million pesos or si crush",
	"KZ or Kyla",
	"Mahal mo o mahal ka",
	"twitter or Instagram",
	"Math or Science",
	"Dolphy or Vice Ganda",
	"Lights on or lights off",
	"Harry Roque or Salvador Panelo",
	"Paksiw na Isda or Isdang Paksiw",
	"Mister Donut or Dunkin Donuts",
	"Beauty or Brains",
	"Free coffee or Free Wifi",
	"Ketchup or Mustard",
	"Coke or Pepsi",
	"Dogs or Cats",
	"Kalapati or Kahit anong Ibon",
	"Android or Iphone",
	"Desktop or Laptop",
	"Call or Chat",
	"Older than you or Younger than you",
	"Umaaraw or Umuulan",
	"Groovy or Rythm",
	"Mcdo or Jollibee",
	"Torpe or Aggressive",
	"Earphones or Headphones",
	"Nutella or Peanut Butter",
	"Willie Revillame or Jovit Baldivino",
	"Early Bird or Night Owl",
	"Beach or Mountains",
	"Tall or Short",
	"Coffee or Tea",
	"Left or Right",
	"Taylor Swift or Kuya Wil",
	"Painting or Drawing",
	"Mawala wallet or Mawala cellphone",
	"Bumalik sa Past or Makita ang Future",
	"Mawala ka or Mawala Ako",
	"LDR; Magwowork or Hindi Magwowork",
	"Fruits or Veggies",
	"Sweet or Savory",
	"North or South",
	"Apple or Banana",
	"Hot or Cold",
	"In or Out",
	"Friend or Lover",
	"Glass half empty or half full",
	"Wet or Dry",
	"Grabfood or Foodpanda",
	"Shakey's or Pizza Hut",
	"BBQ or Cheese",
	"Beer or Wine",
	"Swim sa Beach or Swim sa Pool",
	"Chips Ahoy or Oreos",
	"Travel with best friend or Travel with Jowa",
	"Young at heart or Old soul",
	"Naughty or Nice",
	"Sing or Dance",
	"Piercings or Tattoos",
	"Sandals or Sneakers",
	"For Christmas: Bagong Damit or Bagong Phone",
	"Pinakaayaw: Maghugas ng pinggan or Maglaba",
	"Work alone or Work with a team",
	"Intelligent or Funny",
	"Curly Hair or Straight Hair",
	"Credit Card or Cash",
	"Skydiving or Bungee Jumping",
	"Rich Friend or Loyal Friend",
	"Sunrise or Sunset",
	"Makeup or No Makeup",
	"Hot or Pretty",
	"Hugs or Kisses",
	"Instant Death or Prolonged Death",
	"Jowa: Engineer or Architect",
	"Handmade gifts or Expensive gifts",
	"Glasses or Contacts",
	"Nice smile or Nice eyes",
	"Marvel or DC",
	"Worse: Bad breath or Body odor",
	"Beard or Clean-shaved",
	"Spam or Maling",
	"Teks or Pogs",
	"Jowa: Lawyer or Doctor",
	"Mabingi o Mabulag",
	"Bugbog o Dignidad",
	"Harry Potter or Hunger Games",
	"Carbonara or Spaghetti",
	"Break someone’s heart or have your heart broken",
	"Kill or be killed",
	"Zombie outbreak or alien invasion",
	"Be an asshole or a be a liar",
	"Makinig ng bad jokes ni Cai forever o kumain ng Canton with PB ni Crunchie forever",
	"Roller coaster or Ferris Wheel",
	"Isaw na Baboy o Isaw na Manok",
	"Skittles or M&M",
	"Toyo o Suka",
	"Replyan si Ex or Wag Replyan si Ex",
	"Apir or Fist Bump",
	"Dilawan or DDS",
	"Lazada or Shopee",
	"Pera o Bayong",
	"Egg: Sunny Side Up or Scrambled",
	"English or Tagalog",
	"KPOP or JPOP",
	"City or province",
	"Ampalaya o Pasas",
	"Bayan o Sarili",
	"Need or Want",
	"Ano mauuna: sibuyas o bawang?",
	"Console or PC",
	"Alin ang mauuna: Noodles o Seasoning?",
	"Deal or No Deal",
	"Juice or Alcohol",
	"Sisig: With itlog or no itlog",
	"Yakult or Delight",
	"Pet or Plant",
	"Tulfo o Face to Face",
	"Kapamilya or Kapuso",
	"Globe or Smart",
	"MMK o Magpakailanman",
	"Fried or Boiled",
	"Langit o Lupa",
	"Netflix or Youtube",
	"Work Hard or Play hard",
	"Pampatulog: Music or Podcast",
	"Masarap kumain sa bahay: Nakakamay or Naka Utensils",
	"Train Ride or Plane Ride",
	"Madelay yung flight or Mawala bagahe mo",
	"Save or Spend",
	"Horror or Comedy",
	"Card game or Board Game",
	"Dine in Or Pa deliver",
	"Sa pagtulog: Aircon or Electric Fan",
	"Love or Money",
	"Magkaroon ng 3 wishes or Magka lovelife",
	"Sports: Spectator or Participant",
	"Steak or Chicken",
	"Bread: White or Wheat",
	"Coffee: Just Black or With Cream and Sugar",
	"Guitar or Piano",
	"Exercise: Running or Walking",
	"Roses or Sunflowers",
	"Disney World or Universal Studios",
	"Smoker or Non-smoker",
	"Drinking alcohol: Always or Occassional",
	"Magbigay ng gift or Tumanggap ng gift",
	"Dark Chocolate or White Chocolate",
	"Be Loyal or Be faithful",
	"Necklace or Bracelets",
	"Be a superhero or Be a supervillain",
	"Selfie or Group photos",
	"Mas sweet: Kiss sa forehead or kiss sa cheeks",
	"Good morning texts or Good night texts",
	"Game of Thrones or Breaking Bad",
	"Mas masaya: Highschool or College",
	"Nike or Adidas",
	"Eraserheads or Rivermaya",
	"Drumstick or Wings",
	"Fulfill you biggest wish or Resolve your biggest regret",
	"Pick the year you die or Pick the way you die",
	"Continue with your current life or Restart your life",
	"Maingay or Tahimik",
	"Leader or Follower",
	"Help others or Help myself",
	"Makalat or Organized",
	"Book smart or Street smart",
	"Mindset: Life is great or Life can be better",
	"Spontaneous or Planned",
	"Disney or Nickelodeon",
	"Jocks or Nerds",
	"American Eagle or Forever 21",
	"Leonardo Dicaprio or Orlando Bloom",
	"Vans or Keds",
	"Gal Gadot or Megan Fox",
	"Stripes or Polka Dots",
	"Tamagotchi or Furby",
	"Powers: Invisibility or Flight",
	"Ending to a movie: Happy or Tragic",
	"Play soccer in high heels or Play Basketball in roller skates",
	"Mas bet na friend: Ghost or Vampire",
	"Mas annoying: Children or Old people",
	"Travel: In a fancy car or In a private jet",
	"Worse: Accidentally liking pic ni crush or Running into your ex when you look ugly",
	"Surprises: Yay or Nay",
	"Emma Watson or Emma Roberts",
	"Face your fears or Forget you have them",
	"good news first or Bad news first",
	"Chocnut or Hany",
	"Star Wars or Star Trek",
	"Toy Story or Cars",
	"Tambay: Coffee house or Milktea house",
	"shorts or pants",
	"Ironman or Batman",
	"RomCom or Drama",
	"Suspense or Horror",
	"Darna or Wonderwoman",
	"Viber or Telegram",
	"Holding hands on first date: YES or NO",
	"Matte or Glossy",
	"YouTube Music or Spotify",
	"tomato ketchup or banana ketchup",
	"libing o cremate",
	"mawalan ng kuryente o mawalan ng tubig",
	"masampal o masuntok",
	"sapakan o trashtalkan",
	"Transformers or Voltes V",
	"Taho: straw o diretso higop sa baso",
	"iced or ice blended",
	"SM or Ayala Mall",
	"HIMYM or Friends",
	"Gatas sa champorado: evap o powdered",
	"Milo o Ovaltine",
	"own plane or own yatch",
	"Goldilocks or Red Ribbon",
	"date idea: fancy dinner or homecooked meal",
	"Tobey Maguire or Andrew Garfield",
	"shawarma wrap o shawarma rice",
	"big concert or intimate gig",
	"Subtitles or wala?",
	"unli gravy or unli rice?",
	"manalo sa lotto or work at the perfect job?",
	"PM 1.5 or C1?",
	"Halohalo sa razons or sa mang inasal?",
	"Magnolia or selecta?",
	"spanish bread or pan de coco?",
	"elyu or baler?",
	"surfing IRL or surfing the internet?",
	"purefoods corned beef or delimondo?",
	"lucky me canton or mi goreng?",
	"snake 2 or space impact?",
	"maging panganay or bunso?",
	"makakita ng aswang or ng multo?",
	"baking or cooking?",
	"long hair or short hair?",
	"unli samgyup or unli seafood?",
	"describe your first date in 3 words",
	"describe your perfect date in 3 words",
	"your lifestyle nowadays in 3 words",
	"3 qualities you'd like your partner to have",
	"angel's burger or minute burger?",
	"maging friends with ex or hindi?",
	"how i met your mother or big bang theory?",
	"do you want to have kids in the future or not?",
	"do you want to get married in the future or not?",
	"pinoy spag or italian spag",
	"bakit palaging may cordon bleu at fish fillet sa catering?",
	"tang or eight o'clock",
	"bakit ka seloso/selosa kahit wala namang kayo",
	"may timeframe ba ang panliligaw bago sagutin yung nanliligaw",
	"naniniwala ka ba sa ligaw or hindi",
	"Mga epal: Patulan or Ignore",
	"Ateneo or La Salle",
	"Bagay na kinaiinisan mo sa sarili mo",
	"Bagay na kinaiingitan mo sa ibang tao",
	"Parasailing or White water rafting",
	"Worst pickup line you've ever heard or said",
	"Pineapple on pizza: Yes or No",
	"Maging tanga sa love or maging marupok",
	"Maging lalaki for a day or maging babae for a day",
	"Trapped in an elevator: With ex na walang closure or With crush",
	"What's the one thing you really want but can't afford",
	"Speak multiple languages or Read people's minds",
	"If Digong will have dinner at your place, ano lulutuin mo for him",
	"What's the biggest misconception about you",
	"Memorize mo ba ang multiplication table: Yes or No",
	"Anong food meron sa ref niyo ngayon",
	"What's the very first phone you ever had",
	"Gaano ka katagal maligo",
	"When was the last time lumandi ka",
	"If you could be an expert at something, what would it be",
	"Brown eyes or Blue eyes",
	"Comb or Brush",
	"A good read or A good show",
	"Favorite Starbucks drink",
	"Movie marathon or Color run",
	"Life rewind button or Life pause button",
	"Brand new house or Brand new car",
	"Sneeze all the time or Have hiccups all the time",
	"Lose important documents or Lose every photo on your phone",
	"Shout all the time or Whisper all the time",
	"One pillow or Several pillows",
	"Be a celebrity or Meet your fave celebrity",
	"Stargazing or Morning walks",
	"Free clothes or Free food",
	"Always early or Always late",
	"Have a personal chef or Have a personal trainer",
	"Speak to animals or Speak to the dead",
	"MARRY: someone you don't love or someone who doesn't love you",
	"What keeps you up at night",
	"What's the last thing that made you cry",
	"Own a boat or own a plane",
	"Look like a fish or smell like a fish",
	"Pet: dinosaur or dragon",
	"Eat a whole jar of mayonnaise or drink a cup of hot sauce",
	"Have really small hands or have really big feet",
	"Shave all your hair or Lose all your teeth",
	"skyflakes o magicflakes",
	"Grab or Angkas",
	"Fully booked or NBS",
	"Lakatan o Latundan",
	"tabo o bidet",
	"pag nanalo ka sa lottto babalatuhan mo ba si Aling Nena?",
	"mikmik original o choco",
	"Starbucks o CBTL",
	"kimchi o atsara",
	"puto bumbong o bibingka",
	"Mickey Mouse o Hello Kitty",
];

const firebase = require("firebase/app");
require("firebase/database");

firebase.initializeApp(dbConfig);
const database = firebase.database();
const BASE_REF = "/candies";
// const BASE_REF = "/emojis/movie";

const execute = () => {
	database.ref(BASE_REF).set(null);
	database.ref(BASE_REF).set(candies);
};

execute();
